version: "0.1"
environments:
  - name: master
    branch: master
    mode: pull-request
apps:
  - name: angular-demo
    path: ""
    image-resources: true
    text-resources:
      - path: "*.html"
        format: angular-hardcoded


